Question.create(user_id: '1', title:'Level1', answer:'aabbcc', commentary:'LEVEL1のコメント', question_level_id:'1')
Question.create(user_id: '1', title:'Level2', answer:'aabbcc', commentary:'LEVEL2のコメント', question_level_id:'2')
Question.create(user_id: '1', title:'Level3', answer:'aabbcc', commentary:'LEVEL3のコメント', question_level_id:'3')
Question.create(user_id: '1', title:'Level4', answer:'aabbcc', commentary:'LEVEL4のコメント', question_level_id:'4')
Question.create(user_id: '1', title:'Level5', answer:'aabbcc', commentary:'LEVEL5のコメント', question_level_id:'5')